name: SCA 
on:
  push:
    branches:
      - develop
jobs:
  maven-action-detection:
    runs-on: ubuntu-latest
    # The Dependency Submission API requires write permission
    permissions:
      contents: write
    steps:          
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Submit Dependency Snapshot'
        uses: advanced-security/maven-dependency-submission-action@v1
        
  
  SBOM-action-detection:
    runs-on: ubuntu-latest
    #uses GitHub's dependency graph to automatically build an SBOM in SPDX 2.3 format.
    permissions: read-all
    steps:
      - name: Generate SBOM from dependency Graph
        uses: jhutchings1/sbom-generator@v1.0.0
        id: sbom
        env: 
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v3.1.0
        with: 
          path: ${{steps.sbom.outputs.fileName }}
          name: "SBOM"

